### ISSUE TITLE
plugin doesn't work anymore?

### ISSUE THREAD

**Issue by liif-starstorm** [LazyCat2/masquerade-revolt-plugin#4]
hey there! the plugin worked fine in the past. just pasted it into the console, the client refreshed, and boom, everything worked as expected.

had to reinstall my OS recently and tried the same trick after installing revolt - pasted the code into revite's console - revite did a refresh but the plugin no longer shows up as expected.

not sure why this is or what info i could provide to help with the analysis (i'm just a regular user), but let me know what you need.

thanks!

**Comment by LazyCat2** [comment]
Check if plugin support is enabled in experiments tab. If it is enabled, tell me if there are any errors in console (ctrl + shift + i)

**Comment by liif-starstorm** [comment]
oh goodness. i forgot about having to enable plugin support, i'm so sorry. everything works totally fine, forgive me.
